# -*- coding: utf-8 -*-
"""Praktikum 2 Linked List Dalam Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zxvN94A075AA0UcHLgHcinry_g7Gdd6G

1. Membuat Linked List

Membuat Node
"""

class Node:
  def __init__(self, dataval=None):
    self.dataval = dataval
    self.nextval = None

n1 = Node("Januari")
n2 = Node("Februari")
n3 = Node("Maret")

print(n1.dataval)
print(n2.dataval)
print(n3.dataval)

"""Membuat class linked list"""

class linkedlist:
  def __init__(self):
    self.headval = None

Li = linkedlist()
Li.headval = n1

# Link first Node to second node
Li.headval.nextval = n2

# Link second Node to third node
n2.nextval = n3

"""2. Menelusuri Node dalam Linked List

Menelusuri Linked List
"""

class Node:
  def __init__(self, dataval=None):
    self.dataval = dataval
    self.nextval = None

class linkedlist:
  def __init__(self):
    self.headval = None

# ///////////////////////////////////////// #
  def listprint(self):
    printval = self.headval
    while printval is not None:
      print (printval.dataval)
      printval = printval.nextval
# ///////////////////////////////////////// #

Li = linkedlist()
Li.headval = n1

# Link first Node to second node
Li.headval.nextval = n2

# Link second Node to third node
n2.nextval = n3

# ////////////////////// #
Li.listprint()
# ////////////////////// #

"""## 3. penyisipan node pada linked list

Penyisipan di awal
"""

class Node:
  def __init__(self, dataval=None):
    self.dataval = dataval
    self.nextval = None

# create node
n1 = Node("Januari")
n2 = Node("Februari")
n3 = Node("Maret")

class Linkedlist:
  def __init__(self):
    self.headval = None

# Print the linked list
  def listprint(self):
    printval = self.headval
    while printval is not None:
      print(printval.dataval)
      printval = printval.nextval

# ////////////////////////////////////////////////////////////////////////////////////
# create atribut add begining to Update the new nodes next val to existing node
  def AddBegining(self,newdata):
    NewNode = Node(newdata)
    NewNode.nextval = self.headval
    self.headval = NewNode
# ////////////////////////////////////////////////////////////////////////////////////

Li = Linkedlist()
Li.headval = n1

# Link first node to second node
Li.headval.nextval = n2

# Link second node to third node
n2.nextval = n3

# ///////////////////////
Li.AddBegining("Start")
# ///////////////////////
Li.listprint()

"""Penyisipan di tengah"""

class Node:
  def __init__(self, dataval=None):
    self.dataval = dataval
    self.nextval = None


# create node
n1 = Node("Januari")
n2 = Node("Februari")
n3 = Node("Maret")

class Linkedlist:
  def __init__(self):
    self.headval = None

# print the linkedlist
  def listprint(self):
    printval = self.headval
    while printval is not None:
      print(printval.dataval)
      printval = printval.nextval

# ///////////////////////////////////////////////////////
# Function to add node in the middle
  def AddInbetween(self,mid_node,newdata):
    if mid_node is None:
      print("The mentioned node is absent")
      return
    NewNode = Node(newdata)
    NewNode.nextval = mid_node.nextval
    mid_node.nextval = NewNode
# ///////////////////////////////////////////////////////

Li = Linkedlist()
Li.headval = n1

# Link first Note to second node
Li.headval.nextval = n2

# ////////////////////////////
# add node in the end
Li.AddInbetween(n2,"Middle")
# ////////////////////////////
Li.listprint()

"""penyisipan di akhir"""

class Node:
  def __init__(self, dataval=None):
    self.dataval = dataval
    self.nextval = None

# create node
n1 = Node("Januari")
n2 = Node("Februari")

class Linkedlist:
  def __init__(self):
    self.dataval = None

# Print the linked list
  def listprint(self):
    printval = self.headval
    while printval is not None:
      print(printval.dataval)
      printval = printval.nextval

# ////////////////////////////////////////////////////
# Function to add newnode in the end
  def AddInEnd(self, newdata):
    NewNode = Node(newdata)
    if self.headval is None:
       self.headval = NewNode
       return
    last = self.headval
    while(last.nextval):
      last = last.nextval
    last.nextval=NewNode
# ////////////////////////////////////////////////////

Li = Linkedlist()
Li.headval = n1

# Link first Node to second node
Li.headval.nextval = n2

# ////////////////////////////////////////////////////
# add node in the end
Li.AddInEnd("The last")
# ////////////////////////////////////////////////////
Li.listprint()

"""4. Menghapus node pada linked list

Hapus dengan kata kunci
"""

class Node:
  def __init__(self, dataval=None):
    self.dataval = dataval
    self.nextval = None

class Linkedlist:
  def __init__(self):
    self.headval = None

# Print the linked list
  def listprint(self):
    printval = self.headval
    while printval is not None:
      print(printval.dataval)
      printval = printval.nextval

# Function to add node in the begining
  def AddBegining(self,newdata):
    NewNode = Node(newdata)
# Update the new node next val to existing node
    NewNode.nextval = self.headval
    self.headval = NewNode

# ////////////////////////////////////////////////
# Function to remove node by key
  def RemoveNode(self, Removekey):
    HeadVal = self.headval

    if(HeadVal is not None):
      if(HeadVal.dataval == Removekey):
        self.headval = HeadVal.next
        HeadVal = None
        return
    while(HeadVal is not None):
      if HeadVal.dataval == Removekey:
         break
      prev = HeadVal
      HeadVal = HeadVal.nextval
    if(HeadVal == None):
      return
    prev.nextval = HeadVal.nextval
    HeadVal= None
# ////////////////////////////////////////////////

# create linked list named Li
Li = Linkedlist()

# add node
Li.AddBegining("April")
Li.AddBegining("Maret")
Li.AddBegining("Februari")
print("Sebelum dilakukan remove")
Li.listprint()
print("===================================================")


# ////////////////////////////////////////////////
# remove node by key = "Maret"
Li.RemoveNode("Maret")
# ////////////////////////////////////////////////
print("Setelah dilakukan remove dengan kunci 'Maret'")
Li.listprint()

"""Hapus node diawal"""

class Node:
  def __init__(self, dataval=None):
    self.dataval = dataval
    self.nextval = None

class Linkedlist:
  def __init__(self):
    self.headval = None

# Print the linked list
  def listprint(self):
    printval = self.headval
    while printval is not None:
      print(printval.dataval)
      printval = printval.nextval

# Function to add node in the begining
  def AddBegining(self,newdata):
    NewNode = Node(newdata)
# Update the new node next val to existing node
    NewNode.nextval = self.headval
    self.headval = NewNode

# ////////////////////////////////////////////////
# Function to remove first node
  def RemoveFirst(self):
    afterhead = self.headval
    self.headval = afterhead.nextval
# ////////////////////////////////////////////////

# create linked list named Li
Li = Linkedlist()

# add node
Li.AddBegining("April")
Li.AddBegining("Maret")
Li.AddBegining("Februari")
print("Sebelum dilakukan remove")
Li.listprint()
print("===================================================")


# ////////////////////////////////////////////////
# remove first node
Li.RemoveFirst()
# ////////////////////////////////////////////////
print("Setelah dilakukan remove node pertama")
Li.listprint()

"""Hapus node di akhir"""

class Node:
  def __init__(self, dataval=None):
    self.dataval = dataval
    self.nextval = None

class Linkedlist:
  def __init__(self):
    self.headval = None

# Print the linked list
  def listprint(self):
    printval = self.headval
    while printval is not None:
      print(printval.dataval)
      printval = printval.nextval

# Function to add node in the end
  def AddInEnd(self,newdata):
    NewNode = Node(newdata)
    if self.headval is None:
       self.headval = NewNode
       return
    last = self.headval
    while(last.nextval):
      last = last.nextval
    last.nextval=NewNode

# ////////////////////////////////////////////////
# Function to remove first node
  def RemoveEnd(self):
    last = self.headval
    while(last is not None):
      if last.nextval == None:
        break
      prev = last
      last = last.nextval
    if(last==None):
      return
    prev.nextval = last.nextval
    last = None
# ////////////////////////////////////////////////

# create linked list named Li
Li = Linkedlist()

# add node
Li.AddInEnd("Januari")
Li.AddInEnd("Februari")
Li.AddInEnd("Maret")
print("Sebelum dilakukan remove")
Li.listprint()
print("===================================================")


# ////////////////////////////////////////////////
# remove last node
Li.RemoveEnd()
# ////////////////////////////////////////////////
print("setelah dilakukan remove node akhir")
Li.listprint()

"""LATIHAN"""

# double linkedlist
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        self.prev = None


class DoubleLinkedList:
    def __init__(self):
        self.head = None

    # Membuat 3 node awal
    def create_three_nodes(self):
        node1 = Node("Asep")
        node2 = Node("Budi")
        node3 = Node("Candra")

        # Menghubungkan node
        node1.next = node2
        node2.prev = node1

        node2.next = node3
        node3.prev = node2

        self.head = node1

    # Menampilkan isi list
    def display(self):
        current = self.head
        while current:
            print(current.data, end=" <-> ")
            current = current.next
        print("None")

    # Penyisipan setelah node tertentu (tengah)
    def insert_after(self, target, data):
        current = self.head

        # Mencari node target
        while current and current.data != target:
            current = current.next

        if current is None:
            print("Node tidak ditemukan!")
            return

        new_node = Node(data)

        # Mengatur pointer
        new_node.next = current.next
        new_node.prev = current

        if current.next:
            current.next.prev = new_node

        current.next = new_node

    # Hapus berdasarkan kata kunci
    def delete(self, key):
        current = self.head

        # Mencari node yang akan dihapus
        while current and current.data != key:
            current = current.next

        if current is None:
            print("Node tidak ditemukan!")
            return

        # Jika node pertama
        if current.prev is None:
            self.head = current.next
            if self.head:
                self.head.prev = None
        else:
            current.prev.next = current.next
            if current.next:
                current.next.prev = current.prev


# ===== Program Utama =====
dll = DoubleLinkedList()
dll.create_three_nodes()

print("Sebelum penyisipan:")
dll.display()



print("Setelah penyisipan:")
dll.insert_after("Budi", "Tengah")
dll.display()

dll.delete("Tengah")

print("Setelah penghapusan:")
dll.display()

# circular linked list
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


class CircularLinkedList:
    def __init__(self):
        self.head = None

    def append(self, data):
        new_node = Node(data)

        if not self.head:
            self.head = new_node
            new_node.next = self.head
            return

        temp = self.head
        while temp.next != self.head:
            temp = temp.next

        temp.next = new_node
        new_node.next = self.head

    def delete_end(self):
        if not self.head:
            return

        # Jika hanya 1 node
        if self.head.next == self.head:
            self.head = None
            return

        temp = self.head
        prev = None

        while temp.next != self.head:
            prev = temp
            temp = temp.next

        prev.next = self.head

    def display(self):
        if not self.head:
            print("List kosong")
            return

        temp = self.head
        while True:
            print(temp.data, end=" -> ")
            temp = temp.next
            if temp == self.head:
                break
        print("(kembali ke head)")



# =======Program Utama=======

cll = CircularLinkedList()

# 3 node awal
cll.append('merah')
cll.append('kuning')
cll.append('hijau')

print("Data awal:")
cll.display()

# Tambah akhir
cll.append('ungu')
print("Setelah tambah akhir:")
cll.display()

# Hapus akhir
cll.delete_end()
print("Setelah hapus akhir:")
cll.display()